import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, WidthType, AlignmentType } from "docx";
import { saveAs } from "file-saver";

// Note: file-saver is often needed for docx, but we can use a simple blob approach if not installed.
// I'll use the blob approach to avoid extra dependencies if possible, or I'll install it.
// Actually, I'll just use the standard browser download approach.

export async function exportToPDF(title: string, content: string) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxLineWidth = pageWidth - margin * 2;
  const footerHeight = 15;
  const contentBottomMargin = margin + footerHeight;
  
  let cursorY = 20;

  const addFooter = () => {
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      if (i === 1) continue; // Skip footer on cover page
      doc.setPage(i);
      doc.setFont("helvetica", "italic");
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      const date = new Date().toLocaleDateString();
      const footerText = `Generated by DocuForge AI on ${date} | Page ${i} of ${pageCount}`;
      doc.text(footerText, pageWidth / 2, pageHeight - 10, { align: "center" });
    }
  };

  const checkPageBreak = (neededHeight: number) => {
    if (cursorY + neededHeight > pageHeight - contentBottomMargin) {
      doc.addPage();
      cursorY = margin;
      return true;
    }
    return false;
  };

  // --- CONTENT PAGES ---
  const lines = content.split("\n");
  let i = 0;

  const stripMarkdown = (text: string) => {
    return text.replace(/!\[.*?\]\(.*?\)/g, "") // Images
               .replace(/\[(.*?)\]\(.*?\)/g, "$1") // Links
               .replace(/\*\*(.*?)\*\*/g, "$1") // Bold
               .replace(/\*(.*?)\*/g, "$1")     // Italic
               .replace(/__(.*?)__/g, "$1")     // Bold underscore
               .replace(/_(.*?)_/g, "$1")       // Italic underscore
               .replace(/`(.*?)`/g, "$1")       // Inline code
               .replace(/---/g, "")             // HR
               .trim();
  };

  while (i < lines.length) {
    let line = lines[i].trim();

    if (!line) {
      cursorY += 4;
      i++;
      continue;
    }

    // Detect Horizontal Rule
    if (line === "---" || line === "***" || line === "___") {
      doc.addPage();
      cursorY = margin;
      i++;
      continue;
    }

    // Detect Table
    if (line.includes("|") && lines[i + 1]?.includes("|")) {
      const isSeparator = (l: string) => {
        const trimmed = l.trim();
        return trimmed.includes("|") && 
               trimmed.replace(/[|:\-\s]/g, "").length === 0 && 
               trimmed.includes("-");
      };
      
      if (isSeparator(lines[i + 1])) {
        const tableRows: string[][] = [];
        // Improved split to handle empty cells correctly
        const headers = line.split("|")
          .map(cell => cell.trim())
          .filter((cell, index, array) => {
            // Remove the first and last empty elements if they exist (from the leading/trailing |)
            if ((index === 0 || index === array.length - 1) && !cell) return false;
            return true;
          })
          .map(cell => stripMarkdown(cell));
          
        i += 2; // Skip header and separator line
        
        while (i < lines.length && lines[i].includes("|")) {
          if (!isSeparator(lines[i])) {
            const row = lines[i].split("|")
              .map(cell => cell.trim())
              .filter((cell, index, array) => {
                if ((index === 0 || index === array.length - 1) && !cell) return false;
                return true;
              })
              .map(cell => stripMarkdown(cell));
            
            if (row.length > 0) tableRows.push(row);
          }
          i++;
        }

        if (headers.length > 0) {
          autoTable(doc, {
            head: [headers],
            body: tableRows,
            startY: cursorY,
            margin: { left: margin, right: margin },
            styles: { fontSize: 9, cellPadding: 3, textColor: [33, 33, 33], overflow: 'linebreak' },
            headStyles: { fillColor: [30, 58, 138], textColor: 255, fontStyle: "bold", halign: 'left' },
            alternateRowStyles: { fillColor: [248, 250, 252] },
            columnStyles: {
              0: { cellWidth: 25 }, // ID column
            },
            didDrawPage: (data) => {
              cursorY = data.cursor?.y || cursorY;
            }
          });
          
          cursorY = (doc as any).lastAutoTable.finalY + 10;
        }
        continue;
      }
    }

    // Detect Headings
    const numberedHeadingMatch = line.match(/^(\d+(\.\d+)*)\.?\s+(.+)$/);
    const isMarkdownHeading = line.startsWith("#");
    
    if (isMarkdownHeading || (numberedHeadingMatch && line.length < 150)) {
      let level = 0;
      let headingText = line;
      
      if (isMarkdownHeading) {
        while (headingText.startsWith("#")) {
          level++;
          headingText = headingText.substring(1);
        }
        headingText = headingText.trim();
        
        // If it's a markdown heading that ALSO has numbering, use the numbering to determine level if it's deeper
        const innerNumberedMatch = headingText.match(/^(\d+(\.\d+)*)\.?\s+(.+)$/);
        if (innerNumberedMatch) {
          const dots = (innerNumberedMatch[1].match(/\./g) || []).length;
          const numberedLevel = dots + 1;
          // We take the max of markdown level and numbered level to be safe
          // But usually, we want to respect the hierarchy.
          // If it's "## 1. Title", level is 2.
        }
      } else if (numberedHeadingMatch) {
        const dots = (numberedHeadingMatch[1].match(/\./g) || []).length;
        level = dots + 1;
      }
      
      if (level > 0 && level <= 6) {
        let fontSize = 11;
        let fontStyle = "normal";
        let textColor = [10, 25, 47]; // Default Navy

        if (level === 1) { 
          fontSize = 22; 
          fontStyle = "bold"; 
          cursorY += 10;
          // Special case for Cover Page title
          if (i === 0 || (i === 1 && !lines[0].trim())) {
            doc.addPage();
            doc.setPage(1);
            doc.setFont("helvetica", "bold");
            doc.setFontSize(28);
            doc.setTextColor(30, 58, 138); // Deep Blue
            
            // Center the title
            const titleText = headingText;
            const splitTitle = doc.splitTextToSize(titleText, pageWidth - 40);
            doc.text(splitTitle, pageWidth / 2, 80, { align: "center" });
            
            doc.setFontSize(16);
            doc.setTextColor(100, 116, 139);
            doc.text("Technical Specification & System Design", pageWidth / 2, 95 + (splitTitle.length * 5), { align: "center" });
            
            doc.setDrawColor(30, 58, 138);
            doc.setLineWidth(1);
            doc.line(40, 110 + (splitTitle.length * 5), pageWidth - 40, 110 + (splitTitle.length * 5));
            
            doc.setFontSize(12);
            doc.setTextColor(51, 65, 85);
            doc.text(`Version: 1.0.0`, 40, 130 + (splitTitle.length * 5));
            doc.text(`Author: DocuForge Senior Architect`, 40, 140 + (splitTitle.length * 5));
            doc.text(`Date: ${new Date().toLocaleDateString()}`, 40, 150 + (splitTitle.length * 5));
            
            doc.setFontSize(10);
            doc.setTextColor(148, 163, 184);
            const notice = "Confidentiality Notice: This document contains proprietary and confidential information. All data submitted is provided in reliance upon its consent not to use or disclose any information contained herein except in the context of its business relationship with the project stakeholders.";
            const splitNotice = doc.splitTextToSize(notice, pageWidth - 80);
            doc.text(splitNotice, 40, 250);
            
            doc.addPage();
            doc.setPage(2);
            cursorY = margin;
            i++;
            continue;
          }
        }
        else if (level === 2) { fontSize = 14; fontStyle = "bold"; cursorY += 6; }
        else if (level === 3) { fontSize = 12; fontStyle = "bold"; cursorY += 4; }
        else { fontSize = 11; fontStyle = "bold"; cursorY += 2; }

        doc.setFont("helvetica", fontStyle);
        doc.setFontSize(fontSize);
        doc.setTextColor(textColor[0], textColor[1], textColor[2]);

        const cleanHeading = stripMarkdown(isMarkdownHeading ? headingText : line);
        const splitText = doc.splitTextToSize(cleanHeading, maxLineWidth);
        checkPageBreak(splitText.length * (fontSize * 0.5) + 6);
        
        doc.text(splitText, margin, cursorY);
        cursorY += splitText.length * (fontSize * 0.5) + 6;
        i++;
        continue;
      }
    }

    // Detect List
    if (line.startsWith("* ") || line.startsWith("- ") || line.startsWith("•") || line.match(/^\d+\.\s/)) {
      // If it's a numbered list but NOT a heading (longer than 150 chars or doesn't look like a heading)
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(33, 33, 33);

      const isNumberedList = line.match(/^\d+\.\s/);
      const bullet = isNumberedList ? line.match(/^\d+\.\s/)?.[0] || "•" : "•";
      const text = line.replace(/^([*•-]\s*|\d+\.\s*)/, "");
      
      const cleanText = stripMarkdown(text);
      if (cleanText) {
        const splitText = doc.splitTextToSize(cleanText, maxLineWidth - 12);
        checkPageBreak(splitText.length * 5 + 2);
        
        doc.text(bullet, margin, cursorY);
        doc.text(splitText, margin + 10, cursorY);
        cursorY += splitText.length * 5 + 2;
      }
      i++;
      continue;
    }

    // Normal Paragraph
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(33, 33, 33);

    let text = stripMarkdown(line);

    if (text) {
      const splitText = doc.splitTextToSize(text, maxLineWidth);
      checkPageBreak(splitText.length * 5 + 4);
      doc.text(splitText, margin, cursorY);
      cursorY += splitText.length * 5 + 4;
    }
    
    i++;
  }
  
  addFooter();
  doc.save(`${title.replace(/\s+/g, "_")}_Documentation.pdf`);
}

export async function exportToWord(title: string, content: string) {
  const lines = content.split("\n");
  const children: any[] = [
    new Paragraph({
      text: title,
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    }),
  ];

  const stripMarkdown = (text: string) => {
    return text.replace(/!\[.*?\]\(.*?\)/g, "") // Images
               .replace(/\[(.*?)\]\(.*?\)/g, "$1") // Links
               .replace(/\*\*(.*?)\*\*/g, "$1") // Bold
               .replace(/\*(.*?)\*/g, "$1")     // Italic
               .replace(/__(.*?)__/g, "$1")     // Bold underscore
               .replace(/_(.*?)_/g, "$1")       // Italic underscore
               .replace(/`(.*?)`/g, "$1")       // Inline code
               .replace(/---/g, "")             // HR
               .trim();
  };

  let i = 0;
  const isNumericHeading = (text: string) => {
    const match = text.match(/^(\d+(?:\.\d+)*)\.\s+(.+)$/);
    if (!match) return null;
    const mainText = match[2].trim();
    if (mainText.length > 80) return null;
    if (text.match(/^\d+\.\s+\d+\./)) return null;
    return match[1];
  };

  while (i < lines.length) {
    const line = lines[i].trim();

    if (!line) {
      i++;
      continue;
    }

    // Headings
    if (line.startsWith("# ")) {
      children.push(new Paragraph({ text: stripMarkdown(line.substring(2)), heading: HeadingLevel.HEADING_1, spacing: { before: 400, after: 200 } }));
      i++;
      continue;
    }
    if (line.startsWith("## ")) {
      children.push(new Paragraph({ text: stripMarkdown(line.substring(3)), heading: HeadingLevel.HEADING_2, spacing: { before: 300, after: 150 } }));
      i++;
      continue;
    }
    if (line.startsWith("### ")) {
      children.push(new Paragraph({ text: stripMarkdown(line.substring(4)), heading: HeadingLevel.HEADING_3, spacing: { before: 200, after: 100 } }));
      i++;
      continue;
    }

    const numericHeading = isNumericHeading(line);
    if (numericHeading) {
      const headingLevel = Math.min(numericHeading.split(".").length, 3);
      const text = stripMarkdown(line.replace(/^\d+(?:\.\d+)*\.\s+/, "")).trim();
      const headingMap = {
        1: HeadingLevel.HEADING_1,
        2: HeadingLevel.HEADING_2,
        3: HeadingLevel.HEADING_3,
      };
      children.push(new Paragraph({ text, heading: headingMap[headingLevel], spacing: { before: 300, after: 150 } }));
      i++;
      continue;
    }

    // Tables
    if (line.includes("|") && lines[i + 1]?.includes("|")) {
      const isSeparator = (l: string) => {
        const trimmed = l.trim();
        return trimmed.includes("|") && 
               trimmed.replace(/[|:\-\s]/g, "").length === 0 && 
               trimmed.includes("-");
      };
      
      if (isSeparator(lines[i + 1])) {
        const headers = line.split("|")
          .map(cell => cell.trim())
          .filter((cell, index, array) => !((index === 0 || index === array.length - 1) && !cell))
          .map(cell => stripMarkdown(cell));
          
        i += 2; // Skip header and separator
        
        const rows: TableRow[] = [
          new TableRow({
            children: headers.map(h => new TableCell({
              children: [new Paragraph({ children: [new TextRun({ text: h, bold: true })] })],
              shading: { fill: "F1F5F9" }
            }))
          })
        ];
        
        while (i < lines.length && lines[i].includes("|")) {
          if (!isSeparator(lines[i])) {
            const cells = lines[i].split("|")
              .map(cell => cell.trim())
              .filter((cell, index, array) => !((index === 0 || index === array.length - 1) && !cell))
              .map(cell => stripMarkdown(cell));
            
            if (cells.length > 0) {
              rows.push(new TableRow({
                children: cells.map(c => new TableCell({
                  children: [new Paragraph({ text: c })]
                }))
              }));
            }
          }
          i++;
        }

        children.push(new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: rows,
        }));
        children.push(new Paragraph({ text: "", spacing: { after: 400 } }));
        continue;
      }
    }

    // Lists
    if (line.startsWith("* ") || line.startsWith("- ") || line.match(/^\d+\.\s/)) {
      const text = line.replace(/^([*•-]\s*|\d+\.\s*)/, "");
      children.push(new Paragraph({
        text: stripMarkdown(text),
        bullet: { level: 0 },
        spacing: { after: 100 }
      }));
      i++;
      continue;
    }

    // Normal Paragraph
    children.push(new Paragraph({
      children: [new TextRun(stripMarkdown(line))],
      spacing: { after: 200 },
    }));
    i++;
  }

  const doc = new Document({
    sections: [{ properties: {}, children }],
  });

  const blob = await Packer.toBlob(doc);
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${title.replace(/\s+/g, "_")}_Documentation.docx`;
  a.click();
  window.URL.revokeObjectURL(url);
}

export function exportToMarkdown(title: string, content: string) {
  const blob = new Blob([`# ${title}\n\n${content}`], { type: "text/markdown" });
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${title.replace(/\s+/g, "_")}_Documentation.md`;
  a.click();
  window.URL.revokeObjectURL(url);
}
